#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Cadash core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
for f in $(cd rtl && ls *.sv | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# fx68k 68000 (GPL-3.0, Jorge Cwik)"
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) "../modules/cpu-fx68k"]'
for f in fx68k.sv fx68kAlu.sv uaddrPla.sv; do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"../modules/cpu-fx68k/$f\"]"
done
echo "# tv80 Z80 (MIT, Guy Hutchison)"
for f in $(cd modules/cpu-tv80 && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/cpu-tv80/$f\"]"
done
echo "# jt51 YM2151 (GPL-3.0, Jose Tejada)"
for f in $(cd modules/sound-jt51 && ls *.v | sort); do
    echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) \"../modules/sound-jt51/$f\"]"
done
} > "$out"
echo "wrote $out"
